<?php defined('SYSPATH') or die('No direct script access.');

return array(
	'application/pdf' => 'PDF: Portable Document Format (.pdf)',
	'application/msword' => 'Microsoft Word Document (.doc)',
	'application/ms-ppt' => 'Microsoft PowerPoint Document (.ppt)' ,
	'application/vnd.ms-excel' => 'Microsoft Excel Spreadsheet (.xls)',
	'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => 'Microsoft Word Document (.docx)',
	'application/vnd.openxmlformats-officedocument.presentationml.presentation' => 'Microsoft PowerPoint Document (.pptx)' ,
	'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' => 'Microsoft Excel Spreadsheet (.xlsx)',
	'image/gif' => 'Graphics Interchange Format Image File (.gif)',
	'image/pjpeg' => 'Progressive JPEG Image File (.jpg, .jpeg)',
	'image/jpeg' => 'JPEG Image File (.jpg, .jpeg)',
	'image/png' => 'PNG (Portable Network Graphics) Image File (.png)',
	'application/x-zip-compressed' => 'Compressed ZIP file (.zip)',
	'application/zip' => 'Compressed ZIP file (.zip)',
	'application/x-sea' => 'Stuffit Self Extracting Archive file (.sea)',
	'application/sea' => 'Stuffit Self Extracting Archive file (.sea)',
	'application/x-stuffit' => 'Stuffit Archive file (.sit)',
	'application/x-sit' => 'Stuffit Archive file (.sit)',
	'text/plain' => 'Plain Text File (.txt)',
	'text/html' => 'Hyper Text Markup Language File (.htm, .html)',
	'image/bmp' => 'Bitmap Image File (.bmp)',
	'image/psd' => 'Adobe Photoshop File (.psd)' ,
	'image/tiff' => 'TIFF File (.tif, .tiff)',
	'image/x-eps' => 'Encapusulated PostScript File (.eps, .epsi, .epsf)',
	'application/postscript' => 'Postscript file (.ps)',
	'application/x-shockwave-flash' => 'Adobe Flash File (.swf)',
	'application/illustrator' => 'Adobe Illustrator File (.ai)',
	'application/photoshop' => 'Adobe Photoshop File (.psd)',
	'image/vnd.dwg' => 'AutoCad Drawing (SoftSource) (.dwg)',
	'image/x-dwg' => 'AutoCad Drawing (SoftSource) (.dwg)',
	'image/vnd.dxf' => 'AutoCad DXF file (SoftSource) (.dxf)',
	'image/x-dxf' => 'AutoCad DXF file (SoftSource) (.dxf)',
);